### PR TITLE
fix(docs): make the Lambda Layer version consistent

### LINKED ISSUE #3494: Bug: Layer version is currently inconsistent
### Expected Behaviour

As of today, the [documentation](https://docs.powertools.aws.dev/lambda/python/latest/) states:

```
You can install Powertools for AWS Lambda (Python) using one of the following options:
Lambda Layer (x86_64): [arn:aws:lambda:{region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:53](https://docs.powertools.aws.dev/lambda/python/latest/#)📋
Lambda Layer (arm64): [arn:aws:lambda:{region}:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:53](https://docs.powertools.aws.dev/lambda/python/latest/#)📋
```

So I would expect that the layer version in all regions would be version 53

### Current Behaviour

Some regions have skewed versions.

image

### Code snippet

```python
N/A
```

### Possible Solution

_No response_

### Steps to Reproduce

Go to the documentation, and look at the list of layer versions

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.7

### Packaging format used

Lambda Layers

### Debugging logs

_No response_

### PR DESCRIPTION
**Pull request by rubenfonseca**
**Issue number:** #3494

### Changes

> Please provide a summary of what's being changed

This PR fixes the inconsistent in the Lambda Layer version in our documentation. Now the layer version should be 54 in all supported regions.

We also updated the layer balancer code to support the most recent versions of Go.

### User experience

> Please share what the user experience looks like before and after this change

After this PR, customers can again use the same Lambda Layer version number across regions.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

- [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
- [x] I have performed a self-review of this change
- [x] Changes have been tested
- [x] Changes are documented
- [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

- [ ] Migration process documented
- [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Review by leandrodamascena — CHANGES_REQUESTED** [review]
Hey @rubenfonseca!

1 - Should we balance the arm64 layer as well?
image

2 - Do you think is it possible to fix the description for new layers v54 in x86_64?

Thanks!

**Comment by rubenfonseca** [comment]
@leandrodamascena fixed everything, ready to look again

File: layer/scripts/layer-balancer/main.go [hunk 1]
```diff
@@ -172,7 +172,7 @@ func balanceRegionToVersion(ctx context.Context, region string, layer *LayerInfo
 					ZipFile: payload,
 				},
 				LayerName:          aws.String(layer.Name),
-				CompatibleRuntimes: []types.Runtime{types.RuntimePython37, types.RuntimePython38, types.RuntimePython39},
+				CompatibleRuntimes: []types.Runtime{types.RuntimePython37, types.RuntimePython38, types.RuntimePython39, types.RuntimePython39, types.RuntimePython310},
```
Comment (leandrodamascena) [inline layer/scripts/layer-balancer/main.go]:
```suggestion
				CompatibleRuntimes: []types.Runtime{types.RuntimePython37, types.RuntimePython38, types.RuntimePython39, types.RuntimePython310, types.RuntimePython311},
```

File: layer/scripts/layer-balancer/main.go [hunk 2]
```diff
@@ -183,7 +183,7 @@ func balanceRegionToVersion(ctx context.Context, region string, layer *LayerInfo
 				},
 				LayerName:               aws.String(layer.Name),
 				CompatibleArchitectures: []types.Architecture{layer.Architecture},
-				CompatibleRuntimes:      []types.Runtime{types.RuntimePython37, types.RuntimePython38, types.RuntimePython39},
+				CompatibleRuntimes:      []types.Runtime{types.RuntimePython37, types.RuntimePython38, types.RuntimePython39, types.RuntimePython39, types.RuntimePython310},
```
Comment (leandrodamascena) [inline layer/scripts/layer-balancer/main.go]:
```suggestion
				CompatibleRuntimes:      []types.Runtime{types.RuntimePython37, types.RuntimePython38, types.RuntimePython39, types.RuntimePython310, types.RuntimePython311},
```

**Review by leandrodamascena — CHANGES_REQUESTED** [review]
Just a last comment and it's good! Thanksss Ruben!!

**Review by leandrodamascena — APPROVED** [review]
APPROVED!
